var searchData=
[
  ['ichatstorage_0',['IChatStorage',['../class_gemini_c_p_p_1_1_i_chat_storage.html',1,'GeminiCPP']]],
  ['id_1',['id',['../struct_gemini_c_p_p_1_1_cached_item_info.html#a9979eda0eced875efd361ef2992f71c2',1,'GeminiCPP::CachedItemInfo::id'],['../struct_gemini_c_p_p_1_1_function_call.html#a73de809e0020c8e14c541c831249c25b',1,'GeminiCPP::FunctionCall::id'],['../struct_gemini_c_p_p_1_1_function_response.html#afaf391b6b739a20cb6d0b876275c68d8',1,'GeminiCPP::FunctionResponse::id']]],
  ['ijsonserializable_2',['IJsonSerializable',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20attributionsourceid_20_3e_3',['IJsonSerializable&lt; AttributionSourceId &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchescancelrequestbody_20_3e_4',['IJsonSerializable&lt; BatchesCancelRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchescancelresponsebody_20_3e_5',['IJsonSerializable&lt; BatchesCancelResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesdeleterequestbody_20_3e_6',['IJsonSerializable&lt; BatchesDeleteRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesdeleteresponsebody_20_3e_7',['IJsonSerializable&lt; BatchesDeleteResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesgetrequestbody_20_3e_8',['IJsonSerializable&lt; BatchesGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesgetresponsebody_20_3e_9',['IJsonSerializable&lt; BatchesGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batcheslistrequestbody_20_3e_10',['IJsonSerializable&lt; BatchesListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batcheslistresponsebody_20_3e_11',['IJsonSerializable&lt; BatchesListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesupdateembedcontentbatchqueryparameters_20_3e_12',['IJsonSerializable&lt; BatchesUpdateEmbedContentBatchQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesupdateembedcontentbatchrequestbody_20_3e_13',['IJsonSerializable&lt; BatchesUpdateEmbedContentBatchRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchstats_20_3e_14',['IJsonSerializable&lt; BatchStats &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20citationmetadata_20_3e_15',['IJsonSerializable&lt; CitationMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20citationsource_20_3e_16',['IJsonSerializable&lt; CitationSource &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20counttokensrequestbody_20_3e_17',['IJsonSerializable&lt; CountTokensRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20counttokensresponsebody_20_3e_18',['IJsonSerializable&lt; CountTokensResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20embedcontentrequest_20_3e_19',['IJsonSerializable&lt; EmbedContentRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20file_20_3e_20',['IJsonSerializable&lt; File &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesdeleterequestbody_20_3e_21',['IJsonSerializable&lt; FilesDeleteRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesdeleteresponsebody_20_3e_22',['IJsonSerializable&lt; FilesDeleteResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesgetrequestbody_20_3e_23',['IJsonSerializable&lt; FilesGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesgetresponsebody_20_3e_24',['IJsonSerializable&lt; FilesGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistqueryparameters_20_3e_25',['IJsonSerializable&lt; FilesListQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistrequestbody_20_3e_26',['IJsonSerializable&lt; FilesListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistresponsebody_20_3e_27',['IJsonSerializable&lt; FilesListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentbatch_20_3e_28',['IJsonSerializable&lt; GenerateContentBatch &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentbatchoutput_20_3e_29',['IJsonSerializable&lt; GenerateContentBatchOutput &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentrequestbody_20_3e_30',['IJsonSerializable&lt; GenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentresponsebody_20_3e_31',['IJsonSerializable&lt; GenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generationconfig_20_3e_32',['IJsonSerializable&lt; GenerationConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingattribution_20_3e_33',['IJsonSerializable&lt; GroundingAttribution &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingchunk_20_3e_34',['IJsonSerializable&lt; GroundingChunk &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingmetadata_20_3e_35',['IJsonSerializable&lt; GroundingMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingpassageid_20_3e_36',['IJsonSerializable&lt; GroundingPassageId &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingsupport_20_3e_37',['IJsonSerializable&lt; GroundingSupport &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20imageconfig_20_3e_38',['IJsonSerializable&lt; ImageConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedrequest_20_3e_39',['IJsonSerializable&lt; InlinedRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedrequests_20_3e_40',['IJsonSerializable&lt; InlinedRequests &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedresponse_20_3e_41',['IJsonSerializable&lt; InlinedResponse &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedresponses_20_3e_42',['IJsonSerializable&lt; InlinedResponses &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inputconfig_20_3e_43',['IJsonSerializable&lt; InputConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20listoperationsrequest_20_3e_44',['IJsonSerializable&lt; ListOperationsRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20listoperationsresponse_20_3e_45',['IJsonSerializable&lt; ListOperationsResponse &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20logprobscandidate_20_3e_46',['IJsonSerializable&lt; LogprobsCandidate &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20logprobsresult_20_3e_47',['IJsonSerializable&lt; LogprobsResult &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20maps_20_3e_48',['IJsonSerializable&lt; Maps &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20mediauploadrequestbody_20_3e_49',['IJsonSerializable&lt; MediaUploadRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20mediauploadresponsebody_20_3e_50',['IJsonSerializable&lt; MediaUploadResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modalitytokencount_20_3e_51',['IJsonSerializable&lt; ModalityTokenCount &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelinfo_20_3e_52',['IJsonSerializable&lt; ModelInfo &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsasyncbatchgeneratecontentrequestbody_20_3e_53',['IJsonSerializable&lt; ModelsAsyncBatchGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsasyncbatchgeneratecontentresponsebody_20_3e_54',['IJsonSerializable&lt; ModelsAsyncBatchGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsbatchgeneratecontentrequestbody_20_3e_55',['IJsonSerializable&lt; ModelsBatchGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsbatchgeneratecontentresponsebody_20_3e_56',['IJsonSerializable&lt; ModelsBatchGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsgetrequestbody_20_3e_57',['IJsonSerializable&lt; ModelsGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsgetresponsebody_20_3e_58',['IJsonSerializable&lt; ModelsGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistqueryparameters_20_3e_59',['IJsonSerializable&lt; ModelsListQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistrequestbody_20_3e_60',['IJsonSerializable&lt; ModelsListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistresponsebody_20_3e_61',['IJsonSerializable&lt; ModelsListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictlongrunningrequestbody_20_3e_62',['IJsonSerializable&lt; ModelsPredictLongRunningRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictlongrunningresponsebody_20_3e_63',['IJsonSerializable&lt; ModelsPredictLongRunningResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictrequestbody_20_3e_64',['IJsonSerializable&lt; ModelsPredictRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictresponsebody_20_3e_65',['IJsonSerializable&lt; ModelsPredictResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20multispeakervoiceconfig_20_3e_66',['IJsonSerializable&lt; MultiSpeakerVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20placeanswersources_20_3e_67',['IJsonSerializable&lt; PlaceAnswerSources &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20prebuiltvoiceconfig_20_3e_68',['IJsonSerializable&lt; PrebuiltVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20promptfeedback_20_3e_69',['IJsonSerializable&lt; PromptFeedback &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20responsecandidate_20_3e_70',['IJsonSerializable&lt; ResponseCandidate &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20retrievalmetadata_20_3e_71',['IJsonSerializable&lt; RetrievalMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20retrievedcontext_20_3e_72',['IJsonSerializable&lt; RetrievedContext &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20reviewsnippet_20_3e_73',['IJsonSerializable&lt; ReviewSnippet &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20safetyrating_20_3e_74',['IJsonSerializable&lt; SafetyRating &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20searchentrypoint_20_3e_75',['IJsonSerializable&lt; SearchEntryPoint &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20segment_20_3e_76',['IJsonSerializable&lt; Segment &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20semanticretrieverchunk_20_3e_77',['IJsonSerializable&lt; SemanticRetrieverChunk &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20speakervoiceconfig_20_3e_78',['IJsonSerializable&lt; SpeakerVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20speechconfig_20_3e_79',['IJsonSerializable&lt; SpeechConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20status_20_3e_80',['IJsonSerializable&lt; Status &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20streamgeneratecontentrequestbody_20_3e_81',['IJsonSerializable&lt; StreamGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20streamgeneratecontentresponsebody_20_3e_82',['IJsonSerializable&lt; StreamGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20thinkingconfig_20_3e_83',['IJsonSerializable&lt; ThinkingConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20toplogprobscandidates_20_3e_84',['IJsonSerializable&lt; TopLogprobsCandidates &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20urlcontextmetadata_20_3e_85',['IJsonSerializable&lt; UrlContextMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20urlmetadata_20_3e_86',['IJsonSerializable&lt; UrlMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20usagemetadata_20_3e_87',['IJsonSerializable&lt; UsageMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20videofilemetadata_20_3e_88',['IJsonSerializable&lt; VideoFileMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20voiceconfig_20_3e_89',['IJsonSerializable&lt; VoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20web_20_3e_90',['IJsonSerializable&lt; Web &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializablebase_91',['IJsonSerializableBase',['../struct_gemini_c_p_p_1_1_i_json_serializable_base.html',1,'GeminiCPP::IJsonSerializableBase'],['../struct_gemini_c_p_p_1_1_i_json_serializable_base.html#a33a5e14171e7ac30e7a60c08e4b3ff56',1,'GeminiCPP::IJsonSerializableBase::IJsonSerializableBase()=default'],['../struct_gemini_c_p_p_1_1_i_json_serializable_base.html#a12c497695248fc4982d27a892bd39413',1,'GeminiCPP::IJsonSerializableBase::IJsonSerializableBase(const IJsonSerializableBase &amp;)=default'],['../struct_gemini_c_p_p_1_1_i_json_serializable_base.html#a670261cbf43f27e63e3453ba575b48bf',1,'GeminiCPP::IJsonSerializableBase::IJsonSerializableBase(IJsonSerializableBase &amp;&amp;)=default']]],
  ['image_92',['image',['../class_gemini_c_p_p_1_1_request_builder.html#a62854ea4a3807ca853ab856b4a1ae5d0',1,'GeminiCPP::RequestBuilder::image()'],['../struct_gemini_c_p_p_1_1_content.html#a72f54cd39a7ffac7d384aab6e5d00ba6',1,'GeminiCPP::Content::image()']]],
  ['image_5fother_93',['IMAGE_OTHER',['../namespace_gemini_c_p_p.html#aadebaef979e34c17fafeac5510100ea2',1,'GeminiCPP']]],
  ['image_5fprohibited_5fcontent_94',['IMAGE_PROHIBITED_CONTENT',['../namespace_gemini_c_p_p.html#ad175bf5bfee7193b77e6a664444e2071',1,'GeminiCPP']]],
  ['image_5frecitation_95',['IMAGE_RECITATION',['../namespace_gemini_c_p_p.html#acd229c94f9b7b145f4c8cbfaad2ae0cb',1,'GeminiCPP']]],
  ['image_5fsafety_96',['IMAGE_SAFETY',['../namespace_gemini_c_p_p.html#a5047a235961ae39d9950d5e804952f6f',1,'GeminiCPP']]],
  ['imageconfig_97',['ImageConfig',['../struct_gemini_c_p_p_1_1_image_config.html',1,'GeminiCPP']]],
  ['imageconfig_98',['imageConfig',['../struct_gemini_c_p_p_1_1_generation_config.html#a299d125bf89eaf3d63d76671a2012a80',1,'GeminiCPP::GenerationConfig']]],
  ['imagesize_99',['ImageSize',['../class_gemini_c_p_p_1_1_support_1_1_image_size.html',1,'GeminiCPP::Support::ImageSize'],['../class_gemini_c_p_p_1_1_support_1_1_image_size.html#aa5f4cd4ebb858f436160a80e0d328369',1,'GeminiCPP::Support::ImageSize::ImageSize()=default'],['../class_gemini_c_p_p_1_1_support_1_1_image_size.html#a99fff70c27be72ba2615cc64765477dd',1,'GeminiCPP::Support::ImageSize::ImageSize(Value v)'],['../class_gemini_c_p_p_1_1_support_1_1_image_size.html#a60fa4ab2e6d10e1d8ff2d07c2fcdd594',1,'GeminiCPP::Support::ImageSize::ImageSize(const std::string &amp;s)'],['../class_gemini_c_p_p_1_1_support_1_1_image_size.html#a1838da482c604a6b5eb867174ed51da8',1,'GeminiCPP::Support::ImageSize::ImageSize(int k)']]],
  ['imagesize_100',['imageSize',['../struct_gemini_c_p_p_1_1_image_config.html#a64d242ef10501404e4b81e32d41f2562',1,'GeminiCPP::ImageConfig']]],
  ['includethoughts_101',['includeThoughts',['../struct_gemini_c_p_p_1_1_thinking_config.html#ab27bd5ddf3934f9050d0d3e302b4c7d4',1,'GeminiCPP::ThinkingConfig']]],
  ['index_102',['index',['../struct_gemini_c_p_p_1_1_response_candidate.html#a0844fad975ac5f75d7e0e8bb15c14bc1',1,'GeminiCPP::ResponseCandidate']]],
  ['init_103',['init',['../class_gemini_c_p_p_1_1_log.html#a12f90d890a262f2c813ed6aa1108674c',1,'GeminiCPP::Log']]],
  ['initialdelayms_104',['initialDelayMs',['../struct_gemini_c_p_p_1_1_support_1_1_retry_config.html#a10a2bf3a532c96d369fcf8e2879d8a03',1,'GeminiCPP::Support::RetryConfig']]],
  ['inlinedrequest_105',['InlinedRequest',['../struct_gemini_c_p_p_1_1_inlined_request.html',1,'GeminiCPP']]],
  ['inlinedrequests_106',['InlinedRequests',['../struct_gemini_c_p_p_1_1_inlined_requests.html',1,'GeminiCPP']]],
  ['inlinedresponse_107',['InlinedResponse',['../struct_gemini_c_p_p_1_1_inlined_response.html',1,'GeminiCPP']]],
  ['inlinedresponses_108',['InlinedResponses',['../struct_gemini_c_p_p_1_1_inlined_responses.html',1,'GeminiCPP']]],
  ['inlinedresponses_109',['inlinedResponses',['../struct_gemini_c_p_p_1_1_inlined_responses.html#af450459fd7c4402527f6138f85f43b47',1,'GeminiCPP::InlinedResponses']]],
  ['inputconfig_110',['InputConfig',['../struct_gemini_c_p_p_1_1_input_config.html',1,'GeminiCPP']]],
  ['inputconfig_111',['inputConfig',['../struct_gemini_c_p_p_1_1_generate_content_batch.html#ab03b6b9dc4fe780318b3089a0a8072a6',1,'GeminiCPP::GenerateContentBatch']]],
  ['inputtokenlimit_112',['inputTokenLimit',['../struct_gemini_c_p_p_1_1_model_info.html#a032f50742d0f00b0924ed62f7692ee6a',1,'GeminiCPP::ModelInfo']]],
  ['inputtokens_113',['inputTokens',['../struct_gemini_c_p_p_1_1_generation_result.html#a9f9f1318e3263a6463b5607272ba71bd',1,'GeminiCPP::GenerationResult']]],
  ['instances_114',['instances',['../struct_gemini_c_p_p_1_1_models_predict_request_body.html#ae9eb68679ba3cc6f9d97eb7e8350e954',1,'GeminiCPP::ModelsPredictRequestBody::instances'],['../struct_gemini_c_p_p_1_1_models_predict_long_running_request_body.html#a3528d84d20d5e6d4b2919ef7732eb1e5',1,'GeminiCPP::ModelsPredictLongRunningRequestBody::instances']]],
  ['invoke_115',['invoke',['../class_gemini_c_p_p_1_1_function_registry.html#ac9667036492de30e19bafaa5e8d14069',1,'GeminiCPP::FunctionRegistry']]],
  ['invoker_116',['invoker',['../struct_gemini_c_p_p_1_1_function_registry_1_1_registered_function.html#ac55e53b2078c51ea8665c68b6463ccd7',1,'GeminiCPP::FunctionRegistry::RegisteredFunction']]],
  ['isblob_117',['isBlob',['../struct_gemini_c_p_p_1_1_part.html#ad2660dc6af05fe0ed4e342e60a46baae',1,'GeminiCPP::Part']]],
  ['iscodeexecutionresult_118',['isCodeExecutionResult',['../struct_gemini_c_p_p_1_1_part.html#ab8a5438e221d74d26ee9da1ffcfef51a',1,'GeminiCPP::Part']]],
  ['isempty_119',['isEmpty',['../class_gemini_c_p_p_1_1_support_1_1_aspect_ratio.html#aa3a469e24993423752925aa732d77531',1,'GeminiCPP::Support::AspectRatio']]],
  ['isexecutablecode_120',['isExecutableCode',['../struct_gemini_c_p_p_1_1_part.html#a93a01b9d0994b4da660465982733833b',1,'GeminiCPP::Part']]],
  ['isfiledata_121',['isFileData',['../struct_gemini_c_p_p_1_1_part.html#a94fe636bb3e1cc4dfc7d0c153c130173',1,'GeminiCPP::Part']]],
  ['isfunctioncall_122',['isFunctionCall',['../struct_gemini_c_p_p_1_1_part.html#a580ab4d8dc644c171cc0b6760bf80f82',1,'GeminiCPP::Part']]],
  ['isfunctionresponse_123',['isFunctionResponse',['../struct_gemini_c_p_p_1_1_part.html#a22198b7b0d953d6e3e5666a8626eea6b',1,'GeminiCPP::Part']]],
  ['isjsonserializable_124',['IsJsonSerializable',['../struct_gemini_c_p_p_1_1_is_json_serializable.html',1,'GeminiCPP']]],
  ['isjsonserializable_3c_20t_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fbase_5fof_5fv_3c_20ijsonserializable_3c_20t_20_3e_2c_20t_20_3e_20_3e_20_3e_125',['IsJsonSerializable&lt; T, std::enable_if_t&lt; std::is_base_of_v&lt; IJsonSerializable&lt; T &gt;, T &gt; &gt; &gt;',['../struct_gemini_c_p_p_1_1_is_json_serializable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__bas80aa3d5ec55c2bad7bffa06d0994fb65.html',1,'GeminiCPP']]],
  ['isretryable_126',['isRetryable',['../class_gemini_c_p_p_1_1_http_mapped_status_code_helper.html#a317c02a2cfdc0e2628c7b0d22024d4c8',1,'GeminiCPP::HttpMappedStatusCodeHelper::isRetryable(int code)'],['../class_gemini_c_p_p_1_1_http_mapped_status_code_helper.html#ab178954af9f9c4c9fd1a0e510906a342',1,'GeminiCPP::HttpMappedStatusCodeHelper::isRetryable(HttpMappedStatusCode code)']]],
  ['issuccess_127',['isSuccess',['../class_gemini_c_p_p_1_1_http_mapped_status_code_helper.html#a4ed10d06c37b464ae232ec12580c4037',1,'GeminiCPP::HttpMappedStatusCodeHelper::isSuccess(int code)'],['../class_gemini_c_p_p_1_1_http_mapped_status_code_helper.html#a17f9af71755122ba2a36e932c59d1ca2',1,'GeminiCPP::HttpMappedStatusCodeHelper::isSuccess(HttpMappedStatusCode code)']]],
  ['istext_128',['isText',['../struct_gemini_c_p_p_1_1_part.html#acfeb60e75648d72d14cb2ffcd561c4f3',1,'GeminiCPP::Part']]],
  ['isvalid_129',['isValid',['../struct_gemini_c_p_p_1_1_support_1_1_api_validation_result.html#a8a7378000b156aac37b010ed4f83b4c4',1,'GeminiCPP::Support::ApiValidationResult::isValid'],['../class_gemini_c_p_p_1_1_support_1_1_timestamp.html#ad39b610feb16a460e3e79f3b604b248b',1,'GeminiCPP::Support::Timestamp::isValid()']]]
];
