var searchData=
[
  ['ichatstorage_0',['IChatStorage',['../class_gemini_c_p_p_1_1_i_chat_storage.html',1,'GeminiCPP']]],
  ['ijsonserializable_1',['IJsonSerializable',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20attributionsourceid_20_3e_2',['IJsonSerializable&lt; AttributionSourceId &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchescancelrequestbody_20_3e_3',['IJsonSerializable&lt; BatchesCancelRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchescancelresponsebody_20_3e_4',['IJsonSerializable&lt; BatchesCancelResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesdeleterequestbody_20_3e_5',['IJsonSerializable&lt; BatchesDeleteRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesdeleteresponsebody_20_3e_6',['IJsonSerializable&lt; BatchesDeleteResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesgetrequestbody_20_3e_7',['IJsonSerializable&lt; BatchesGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesgetresponsebody_20_3e_8',['IJsonSerializable&lt; BatchesGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batcheslistrequestbody_20_3e_9',['IJsonSerializable&lt; BatchesListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batcheslistresponsebody_20_3e_10',['IJsonSerializable&lt; BatchesListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesupdateembedcontentbatchqueryparameters_20_3e_11',['IJsonSerializable&lt; BatchesUpdateEmbedContentBatchQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchesupdateembedcontentbatchrequestbody_20_3e_12',['IJsonSerializable&lt; BatchesUpdateEmbedContentBatchRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20batchstats_20_3e_13',['IJsonSerializable&lt; BatchStats &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20citationmetadata_20_3e_14',['IJsonSerializable&lt; CitationMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20citationsource_20_3e_15',['IJsonSerializable&lt; CitationSource &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20counttokensrequestbody_20_3e_16',['IJsonSerializable&lt; CountTokensRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20counttokensresponsebody_20_3e_17',['IJsonSerializable&lt; CountTokensResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20embedcontentrequest_20_3e_18',['IJsonSerializable&lt; EmbedContentRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20file_20_3e_19',['IJsonSerializable&lt; File &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesdeleterequestbody_20_3e_20',['IJsonSerializable&lt; FilesDeleteRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesdeleteresponsebody_20_3e_21',['IJsonSerializable&lt; FilesDeleteResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesgetrequestbody_20_3e_22',['IJsonSerializable&lt; FilesGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20filesgetresponsebody_20_3e_23',['IJsonSerializable&lt; FilesGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistqueryparameters_20_3e_24',['IJsonSerializable&lt; FilesListQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistrequestbody_20_3e_25',['IJsonSerializable&lt; FilesListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20fileslistresponsebody_20_3e_26',['IJsonSerializable&lt; FilesListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentbatch_20_3e_27',['IJsonSerializable&lt; GenerateContentBatch &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentbatchoutput_20_3e_28',['IJsonSerializable&lt; GenerateContentBatchOutput &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentrequestbody_20_3e_29',['IJsonSerializable&lt; GenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generatecontentresponsebody_20_3e_30',['IJsonSerializable&lt; GenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20generationconfig_20_3e_31',['IJsonSerializable&lt; GenerationConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingattribution_20_3e_32',['IJsonSerializable&lt; GroundingAttribution &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingchunk_20_3e_33',['IJsonSerializable&lt; GroundingChunk &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingmetadata_20_3e_34',['IJsonSerializable&lt; GroundingMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingpassageid_20_3e_35',['IJsonSerializable&lt; GroundingPassageId &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20groundingsupport_20_3e_36',['IJsonSerializable&lt; GroundingSupport &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20imageconfig_20_3e_37',['IJsonSerializable&lt; ImageConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedrequest_20_3e_38',['IJsonSerializable&lt; InlinedRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedrequests_20_3e_39',['IJsonSerializable&lt; InlinedRequests &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedresponse_20_3e_40',['IJsonSerializable&lt; InlinedResponse &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inlinedresponses_20_3e_41',['IJsonSerializable&lt; InlinedResponses &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20inputconfig_20_3e_42',['IJsonSerializable&lt; InputConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20listoperationsrequest_20_3e_43',['IJsonSerializable&lt; ListOperationsRequest &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20listoperationsresponse_20_3e_44',['IJsonSerializable&lt; ListOperationsResponse &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20logprobscandidate_20_3e_45',['IJsonSerializable&lt; LogprobsCandidate &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20logprobsresult_20_3e_46',['IJsonSerializable&lt; LogprobsResult &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20maps_20_3e_47',['IJsonSerializable&lt; Maps &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20mediauploadrequestbody_20_3e_48',['IJsonSerializable&lt; MediaUploadRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20mediauploadresponsebody_20_3e_49',['IJsonSerializable&lt; MediaUploadResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modalitytokencount_20_3e_50',['IJsonSerializable&lt; ModalityTokenCount &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelinfo_20_3e_51',['IJsonSerializable&lt; ModelInfo &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsasyncbatchgeneratecontentrequestbody_20_3e_52',['IJsonSerializable&lt; ModelsAsyncBatchGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsasyncbatchgeneratecontentresponsebody_20_3e_53',['IJsonSerializable&lt; ModelsAsyncBatchGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsbatchgeneratecontentrequestbody_20_3e_54',['IJsonSerializable&lt; ModelsBatchGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsbatchgeneratecontentresponsebody_20_3e_55',['IJsonSerializable&lt; ModelsBatchGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsgetrequestbody_20_3e_56',['IJsonSerializable&lt; ModelsGetRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelsgetresponsebody_20_3e_57',['IJsonSerializable&lt; ModelsGetResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistqueryparameters_20_3e_58',['IJsonSerializable&lt; ModelsListQueryParameters &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistrequestbody_20_3e_59',['IJsonSerializable&lt; ModelsListRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelslistresponsebody_20_3e_60',['IJsonSerializable&lt; ModelsListResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictlongrunningrequestbody_20_3e_61',['IJsonSerializable&lt; ModelsPredictLongRunningRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictlongrunningresponsebody_20_3e_62',['IJsonSerializable&lt; ModelsPredictLongRunningResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictrequestbody_20_3e_63',['IJsonSerializable&lt; ModelsPredictRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20modelspredictresponsebody_20_3e_64',['IJsonSerializable&lt; ModelsPredictResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20multispeakervoiceconfig_20_3e_65',['IJsonSerializable&lt; MultiSpeakerVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20placeanswersources_20_3e_66',['IJsonSerializable&lt; PlaceAnswerSources &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20prebuiltvoiceconfig_20_3e_67',['IJsonSerializable&lt; PrebuiltVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20promptfeedback_20_3e_68',['IJsonSerializable&lt; PromptFeedback &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20responsecandidate_20_3e_69',['IJsonSerializable&lt; ResponseCandidate &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20retrievalmetadata_20_3e_70',['IJsonSerializable&lt; RetrievalMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20retrievedcontext_20_3e_71',['IJsonSerializable&lt; RetrievedContext &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20reviewsnippet_20_3e_72',['IJsonSerializable&lt; ReviewSnippet &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20safetyrating_20_3e_73',['IJsonSerializable&lt; SafetyRating &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20searchentrypoint_20_3e_74',['IJsonSerializable&lt; SearchEntryPoint &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20segment_20_3e_75',['IJsonSerializable&lt; Segment &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20semanticretrieverchunk_20_3e_76',['IJsonSerializable&lt; SemanticRetrieverChunk &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20speakervoiceconfig_20_3e_77',['IJsonSerializable&lt; SpeakerVoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20speechconfig_20_3e_78',['IJsonSerializable&lt; SpeechConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20status_20_3e_79',['IJsonSerializable&lt; Status &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20streamgeneratecontentrequestbody_20_3e_80',['IJsonSerializable&lt; StreamGenerateContentRequestBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20streamgeneratecontentresponsebody_20_3e_81',['IJsonSerializable&lt; StreamGenerateContentResponseBody &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20thinkingconfig_20_3e_82',['IJsonSerializable&lt; ThinkingConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20toplogprobscandidates_20_3e_83',['IJsonSerializable&lt; TopLogprobsCandidates &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20urlcontextmetadata_20_3e_84',['IJsonSerializable&lt; UrlContextMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20urlmetadata_20_3e_85',['IJsonSerializable&lt; UrlMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20usagemetadata_20_3e_86',['IJsonSerializable&lt; UsageMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20videofilemetadata_20_3e_87',['IJsonSerializable&lt; VideoFileMetadata &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20voiceconfig_20_3e_88',['IJsonSerializable&lt; VoiceConfig &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializable_3c_20web_20_3e_89',['IJsonSerializable&lt; Web &gt;',['../struct_gemini_c_p_p_1_1_i_json_serializable.html',1,'GeminiCPP']]],
  ['ijsonserializablebase_90',['IJsonSerializableBase',['../struct_gemini_c_p_p_1_1_i_json_serializable_base.html',1,'GeminiCPP']]],
  ['imageconfig_91',['ImageConfig',['../struct_gemini_c_p_p_1_1_image_config.html',1,'GeminiCPP']]],
  ['imagesize_92',['ImageSize',['../class_gemini_c_p_p_1_1_support_1_1_image_size.html',1,'GeminiCPP::Support']]],
  ['inlinedrequest_93',['InlinedRequest',['../struct_gemini_c_p_p_1_1_inlined_request.html',1,'GeminiCPP']]],
  ['inlinedrequests_94',['InlinedRequests',['../struct_gemini_c_p_p_1_1_inlined_requests.html',1,'GeminiCPP']]],
  ['inlinedresponse_95',['InlinedResponse',['../struct_gemini_c_p_p_1_1_inlined_response.html',1,'GeminiCPP']]],
  ['inlinedresponses_96',['InlinedResponses',['../struct_gemini_c_p_p_1_1_inlined_responses.html',1,'GeminiCPP']]],
  ['inputconfig_97',['InputConfig',['../struct_gemini_c_p_p_1_1_input_config.html',1,'GeminiCPP']]],
  ['isjsonserializable_98',['IsJsonSerializable',['../struct_gemini_c_p_p_1_1_is_json_serializable.html',1,'GeminiCPP']]],
  ['isjsonserializable_3c_20t_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fbase_5fof_5fv_3c_20ijsonserializable_3c_20t_20_3e_2c_20t_20_3e_20_3e_20_3e_99',['IsJsonSerializable&lt; T, std::enable_if_t&lt; std::is_base_of_v&lt; IJsonSerializable&lt; T &gt;, T &gt; &gt; &gt;',['../struct_gemini_c_p_p_1_1_is_json_serializable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__bas80aa3d5ec55c2bad7bffa06d0994fb65.html',1,'GeminiCPP']]]
];
