var annotated_dup =
[
    [ "GeminiCPP", "namespace_gemini_c_p_p.html", [
      [ "Internal", "namespace_gemini_c_p_p_1_1_internal.html", [
        [ "JsonTypeTraits", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits.html", null ],
        [ "JsonTypeTraits&lt; std::string &gt;", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits_3_01std_1_1string_01_4.html", null ],
        [ "JsonTypeTraits&lt; const char * &gt;", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits_3_01const_01char_01_5_01_4.html", null ],
        [ "JsonTypeTraits&lt; T &gt;", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits_3_01_t_01_4.html", null ],
        [ "JsonTypeTraits&lt; bool &gt;", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits_3_01bool_01_4.html", null ],
        [ "JsonTypeTraits&lt; std::vector&lt; T &gt; &gt;", "struct_gemini_c_p_p_1_1_internal_1_1_json_type_traits_3_01std_1_1vector_3_01_t_01_4_01_4.html", null ]
      ] ],
      [ "Support", "namespace_gemini_c_p_p_1_1_support.html", [
        [ "RetryConfig", "struct_gemini_c_p_p_1_1_support_1_1_retry_config.html", "struct_gemini_c_p_p_1_1_support_1_1_retry_config" ],
        [ "ApiValidationResult", "struct_gemini_c_p_p_1_1_support_1_1_api_validation_result.html", "struct_gemini_c_p_p_1_1_support_1_1_api_validation_result" ],
        [ "AspectRatio", "class_gemini_c_p_p_1_1_support_1_1_aspect_ratio.html", "class_gemini_c_p_p_1_1_support_1_1_aspect_ratio" ],
        [ "ImageSize", "class_gemini_c_p_p_1_1_support_1_1_image_size.html", "class_gemini_c_p_p_1_1_support_1_1_image_size" ],
        [ "LanguageCode", "class_gemini_c_p_p_1_1_support_1_1_language_code.html", "class_gemini_c_p_p_1_1_support_1_1_language_code" ],
        [ "Base64String", "class_gemini_c_p_p_1_1_support_1_1_base64_string.html", "class_gemini_c_p_p_1_1_support_1_1_base64_string" ],
        [ "Timestamp", "class_gemini_c_p_p_1_1_support_1_1_timestamp.html", "class_gemini_c_p_p_1_1_support_1_1_timestamp" ],
        [ "FieldMask", "class_gemini_c_p_p_1_1_support_1_1_field_mask.html", "class_gemini_c_p_p_1_1_support_1_1_field_mask" ]
      ] ],
      [ "Files", "class_gemini_c_p_p_1_1_files.html", "class_gemini_c_p_p_1_1_files" ],
      [ "Models", "class_gemini_c_p_p_1_1_models.html", "class_gemini_c_p_p_1_1_models" ],
      [ "Tokens", "class_gemini_c_p_p_1_1_tokens.html", "class_gemini_c_p_p_1_1_tokens" ],
      [ "CachedItemInfo", "struct_gemini_c_p_p_1_1_cached_item_info.html", "struct_gemini_c_p_p_1_1_cached_item_info" ],
      [ "CacheRegistry", "class_gemini_c_p_p_1_1_cache_registry.html", "class_gemini_c_p_p_1_1_cache_registry" ],
      [ "ChatSession", "class_gemini_c_p_p_1_1_chat_session.html", "class_gemini_c_p_p_1_1_chat_session" ],
      [ "Client", "class_gemini_c_p_p_1_1_client.html", "class_gemini_c_p_p_1_1_client" ],
      [ "Duration", "struct_gemini_c_p_p_1_1_duration.html", "struct_gemini_c_p_p_1_1_duration" ],
      [ "FunctionRegistry", "class_gemini_c_p_p_1_1_function_registry.html", "class_gemini_c_p_p_1_1_function_registry" ],
      [ "GenerationMethodHelper", "struct_gemini_c_p_p_1_1_generation_method_helper.html", null ],
      [ "HttpMappedStatusCodeHelper", "class_gemini_c_p_p_1_1_http_mapped_status_code_helper.html", null ],
      [ "Log", "class_gemini_c_p_p_1_1_log.html", null ],
      [ "RequestBuilder", "class_gemini_c_p_p_1_1_request_builder.html", "class_gemini_c_p_p_1_1_request_builder" ],
      [ "Result", "struct_gemini_c_p_p_1_1_result.html", "struct_gemini_c_p_p_1_1_result" ],
      [ "GenerationResult", "struct_gemini_c_p_p_1_1_generation_result.html", "struct_gemini_c_p_p_1_1_generation_result" ],
      [ "IChatStorage", "class_gemini_c_p_p_1_1_i_chat_storage.html", "class_gemini_c_p_p_1_1_i_chat_storage" ],
      [ "LocalStorage", "class_gemini_c_p_p_1_1_local_storage.html", "class_gemini_c_p_p_1_1_local_storage" ],
      [ "RemoteStorage", "class_gemini_c_p_p_1_1_remote_storage.html", "class_gemini_c_p_p_1_1_remote_storage" ],
      [ "ListOperationsRequest", "struct_gemini_c_p_p_1_1_list_operations_request.html", "struct_gemini_c_p_p_1_1_list_operations_request" ],
      [ "ListOperationsResponse", "struct_gemini_c_p_p_1_1_list_operations_response.html", "struct_gemini_c_p_p_1_1_list_operations_response" ],
      [ "EmbedContentRequest", "struct_gemini_c_p_p_1_1_embed_content_request.html", "struct_gemini_c_p_p_1_1_embed_content_request" ],
      [ "BatchStats", "struct_gemini_c_p_p_1_1_batch_stats.html", "struct_gemini_c_p_p_1_1_batch_stats" ],
      [ "InlinedResponse", "struct_gemini_c_p_p_1_1_inlined_response.html", "struct_gemini_c_p_p_1_1_inlined_response" ],
      [ "InlinedResponses", "struct_gemini_c_p_p_1_1_inlined_responses.html", "struct_gemini_c_p_p_1_1_inlined_responses" ],
      [ "GenerateContentBatchOutput", "struct_gemini_c_p_p_1_1_generate_content_batch_output.html", "struct_gemini_c_p_p_1_1_generate_content_batch_output" ],
      [ "InlinedRequest", "struct_gemini_c_p_p_1_1_inlined_request.html", "struct_gemini_c_p_p_1_1_inlined_request" ],
      [ "InlinedRequests", "struct_gemini_c_p_p_1_1_inlined_requests.html", "struct_gemini_c_p_p_1_1_inlined_requests" ],
      [ "InputConfig", "struct_gemini_c_p_p_1_1_input_config.html", "struct_gemini_c_p_p_1_1_input_config" ],
      [ "GenerateContentBatch", "struct_gemini_c_p_p_1_1_generate_content_batch.html", "struct_gemini_c_p_p_1_1_generate_content_batch" ],
      [ "ModelsBatchGenerateContentRequestBody", "struct_gemini_c_p_p_1_1_models_batch_generate_content_request_body.html", "struct_gemini_c_p_p_1_1_models_batch_generate_content_request_body" ],
      [ "ModelsBatchGenerateContentResponseBody", "struct_gemini_c_p_p_1_1_models_batch_generate_content_response_body.html", "struct_gemini_c_p_p_1_1_models_batch_generate_content_response_body" ],
      [ "ModelsAsyncBatchGenerateContentRequestBody", "struct_gemini_c_p_p_1_1_models_async_batch_generate_content_request_body.html", "struct_gemini_c_p_p_1_1_models_async_batch_generate_content_request_body" ],
      [ "ModelsAsyncBatchGenerateContentResponseBody", "struct_gemini_c_p_p_1_1_models_async_batch_generate_content_response_body.html", "struct_gemini_c_p_p_1_1_models_async_batch_generate_content_response_body" ],
      [ "BatchesGetRequestBody", "struct_gemini_c_p_p_1_1_batches_get_request_body.html", "struct_gemini_c_p_p_1_1_batches_get_request_body" ],
      [ "BatchesGetResponseBody", "struct_gemini_c_p_p_1_1_batches_get_response_body.html", "struct_gemini_c_p_p_1_1_batches_get_response_body" ],
      [ "BatchesListRequestBody", "struct_gemini_c_p_p_1_1_batches_list_request_body.html", "struct_gemini_c_p_p_1_1_batches_list_request_body" ],
      [ "BatchesListResponseBody", "struct_gemini_c_p_p_1_1_batches_list_response_body.html", "struct_gemini_c_p_p_1_1_batches_list_response_body" ],
      [ "BatchesCancelRequestBody", "struct_gemini_c_p_p_1_1_batches_cancel_request_body.html", "struct_gemini_c_p_p_1_1_batches_cancel_request_body" ],
      [ "BatchesCancelResponseBody", "struct_gemini_c_p_p_1_1_batches_cancel_response_body.html", "struct_gemini_c_p_p_1_1_batches_cancel_response_body" ],
      [ "BatchesDeleteRequestBody", "struct_gemini_c_p_p_1_1_batches_delete_request_body.html", "struct_gemini_c_p_p_1_1_batches_delete_request_body" ],
      [ "BatchesDeleteResponseBody", "struct_gemini_c_p_p_1_1_batches_delete_response_body.html", "struct_gemini_c_p_p_1_1_batches_delete_response_body" ],
      [ "BatchesUpdateEmbedContentBatchQueryParameters", "struct_gemini_c_p_p_1_1_batches_update_embed_content_batch_query_parameters.html", "struct_gemini_c_p_p_1_1_batches_update_embed_content_batch_query_parameters" ],
      [ "BatchesUpdateEmbedContentBatchRequestBody", "struct_gemini_c_p_p_1_1_batches_update_embed_content_batch_request_body.html", "struct_gemini_c_p_p_1_1_batches_update_embed_content_batch_request_body" ],
      [ "FunctionResponsePart", "struct_gemini_c_p_p_1_1_function_response_part.html", "struct_gemini_c_p_p_1_1_function_response_part" ],
      [ "TextData", "struct_gemini_c_p_p_1_1_text_data.html", "struct_gemini_c_p_p_1_1_text_data" ],
      [ "Blob", "struct_gemini_c_p_p_1_1_blob.html", "struct_gemini_c_p_p_1_1_blob" ],
      [ "FunctionCall", "struct_gemini_c_p_p_1_1_function_call.html", "struct_gemini_c_p_p_1_1_function_call" ],
      [ "FunctionResponse", "struct_gemini_c_p_p_1_1_function_response.html", "struct_gemini_c_p_p_1_1_function_response" ],
      [ "FileData", "struct_gemini_c_p_p_1_1_file_data.html", "struct_gemini_c_p_p_1_1_file_data" ],
      [ "ExecutableCode", "struct_gemini_c_p_p_1_1_executable_code.html", "struct_gemini_c_p_p_1_1_executable_code" ],
      [ "CodeExecutionResult", "struct_gemini_c_p_p_1_1_code_execution_result.html", "struct_gemini_c_p_p_1_1_code_execution_result" ],
      [ "VideoMetadata", "struct_gemini_c_p_p_1_1_video_metadata.html", "struct_gemini_c_p_p_1_1_video_metadata" ],
      [ "Part", "struct_gemini_c_p_p_1_1_part.html", "struct_gemini_c_p_p_1_1_part" ],
      [ "Content", "struct_gemini_c_p_p_1_1_content.html", "struct_gemini_c_p_p_1_1_content" ],
      [ "FunctionCallingConfig", "struct_gemini_c_p_p_1_1_function_calling_config.html", "struct_gemini_c_p_p_1_1_function_calling_config" ],
      [ "LatLng", "struct_gemini_c_p_p_1_1_lat_lng.html", "struct_gemini_c_p_p_1_1_lat_lng" ],
      [ "RetrievalConfig", "struct_gemini_c_p_p_1_1_retrieval_config.html", "struct_gemini_c_p_p_1_1_retrieval_config" ],
      [ "ToolConfig", "struct_gemini_c_p_p_1_1_tool_config.html", "struct_gemini_c_p_p_1_1_tool_config" ],
      [ "FunctionDeclaration", "struct_gemini_c_p_p_1_1_function_declaration.html", "struct_gemini_c_p_p_1_1_function_declaration" ],
      [ "GoogleSearch", "struct_gemini_c_p_p_1_1_google_search.html", "struct_gemini_c_p_p_1_1_google_search" ],
      [ "GoogleMaps", "struct_gemini_c_p_p_1_1_google_maps.html", "struct_gemini_c_p_p_1_1_google_maps" ],
      [ "CodeExecution", "struct_gemini_c_p_p_1_1_code_execution.html", "struct_gemini_c_p_p_1_1_code_execution" ],
      [ "Tool", "struct_gemini_c_p_p_1_1_tool.html", "struct_gemini_c_p_p_1_1_tool" ],
      [ "CachedContentUsageMetadata", "struct_gemini_c_p_p_1_1_cached_content_usage_metadata.html", "struct_gemini_c_p_p_1_1_cached_content_usage_metadata" ],
      [ "CachedContent", "struct_gemini_c_p_p_1_1_cached_content.html", "struct_gemini_c_p_p_1_1_cached_content" ],
      [ "ListCachedContentsResponse", "struct_gemini_c_p_p_1_1_list_cached_contents_response.html", "struct_gemini_c_p_p_1_1_list_cached_contents_response" ],
      [ "ContentEmbedding", "struct_gemini_c_p_p_1_1_content_embedding.html", "struct_gemini_c_p_p_1_1_content_embedding" ],
      [ "EmbedContentResponse", "struct_gemini_c_p_p_1_1_embed_content_response.html", "struct_gemini_c_p_p_1_1_embed_content_response" ],
      [ "BatchEmbedContentsResponse", "struct_gemini_c_p_p_1_1_batch_embed_contents_response.html", "struct_gemini_c_p_p_1_1_batch_embed_contents_response" ],
      [ "Status", "struct_gemini_c_p_p_1_1_status.html", "struct_gemini_c_p_p_1_1_status" ],
      [ "VideoFileMetadata", "struct_gemini_c_p_p_1_1_video_file_metadata.html", "struct_gemini_c_p_p_1_1_video_file_metadata" ],
      [ "File", "struct_gemini_c_p_p_1_1_file.html", "struct_gemini_c_p_p_1_1_file" ],
      [ "MediaUploadRequestBody", "struct_gemini_c_p_p_1_1_media_upload_request_body.html", "struct_gemini_c_p_p_1_1_media_upload_request_body" ],
      [ "MediaUploadResponseBody", "struct_gemini_c_p_p_1_1_media_upload_response_body.html", "struct_gemini_c_p_p_1_1_media_upload_response_body" ],
      [ "FilesGetRequestBody", "struct_gemini_c_p_p_1_1_files_get_request_body.html", "struct_gemini_c_p_p_1_1_files_get_request_body" ],
      [ "FilesGetResponseBody", "struct_gemini_c_p_p_1_1_files_get_response_body.html", "struct_gemini_c_p_p_1_1_files_get_response_body" ],
      [ "FilesListQueryParameters", "struct_gemini_c_p_p_1_1_files_list_query_parameters.html", "struct_gemini_c_p_p_1_1_files_list_query_parameters" ],
      [ "FilesListRequestBody", "struct_gemini_c_p_p_1_1_files_list_request_body.html", "struct_gemini_c_p_p_1_1_files_list_request_body" ],
      [ "FilesListResponseBody", "struct_gemini_c_p_p_1_1_files_list_response_body.html", "struct_gemini_c_p_p_1_1_files_list_response_body" ],
      [ "FilesDeleteRequestBody", "struct_gemini_c_p_p_1_1_files_delete_request_body.html", "struct_gemini_c_p_p_1_1_files_delete_request_body" ],
      [ "FilesDeleteResponseBody", "struct_gemini_c_p_p_1_1_files_delete_response_body.html", "struct_gemini_c_p_p_1_1_files_delete_response_body" ],
      [ "SafetyRating", "struct_gemini_c_p_p_1_1_safety_rating.html", "struct_gemini_c_p_p_1_1_safety_rating" ],
      [ "ModalityTokenCount", "struct_gemini_c_p_p_1_1_modality_token_count.html", "struct_gemini_c_p_p_1_1_modality_token_count" ],
      [ "ImageConfig", "struct_gemini_c_p_p_1_1_image_config.html", "struct_gemini_c_p_p_1_1_image_config" ],
      [ "ThinkingConfig", "struct_gemini_c_p_p_1_1_thinking_config.html", "struct_gemini_c_p_p_1_1_thinking_config" ],
      [ "PrebuiltVoiceConfig", "struct_gemini_c_p_p_1_1_prebuilt_voice_config.html", "struct_gemini_c_p_p_1_1_prebuilt_voice_config" ],
      [ "VoiceConfig", "struct_gemini_c_p_p_1_1_voice_config.html", "struct_gemini_c_p_p_1_1_voice_config" ],
      [ "SpeakerVoiceConfig", "struct_gemini_c_p_p_1_1_speaker_voice_config.html", "struct_gemini_c_p_p_1_1_speaker_voice_config" ],
      [ "MultiSpeakerVoiceConfig", "struct_gemini_c_p_p_1_1_multi_speaker_voice_config.html", "struct_gemini_c_p_p_1_1_multi_speaker_voice_config" ],
      [ "SpeechConfig", "struct_gemini_c_p_p_1_1_speech_config.html", "struct_gemini_c_p_p_1_1_speech_config" ],
      [ "GenerationConfig", "struct_gemini_c_p_p_1_1_generation_config.html", "struct_gemini_c_p_p_1_1_generation_config" ],
      [ "CitationSource", "struct_gemini_c_p_p_1_1_citation_source.html", "struct_gemini_c_p_p_1_1_citation_source" ],
      [ "CitationMetadata", "struct_gemini_c_p_p_1_1_citation_metadata.html", "struct_gemini_c_p_p_1_1_citation_metadata" ],
      [ "UrlMetadata", "struct_gemini_c_p_p_1_1_url_metadata.html", "struct_gemini_c_p_p_1_1_url_metadata" ],
      [ "UrlContextMetadata", "struct_gemini_c_p_p_1_1_url_context_metadata.html", "struct_gemini_c_p_p_1_1_url_context_metadata" ],
      [ "LogprobsCandidate", "struct_gemini_c_p_p_1_1_logprobs_candidate.html", "struct_gemini_c_p_p_1_1_logprobs_candidate" ],
      [ "TopLogprobsCandidates", "struct_gemini_c_p_p_1_1_top_logprobs_candidates.html", "struct_gemini_c_p_p_1_1_top_logprobs_candidates" ],
      [ "LogprobsResult", "struct_gemini_c_p_p_1_1_logprobs_result.html", "struct_gemini_c_p_p_1_1_logprobs_result" ],
      [ "RetrievalMetadata", "struct_gemini_c_p_p_1_1_retrieval_metadata.html", "struct_gemini_c_p_p_1_1_retrieval_metadata" ],
      [ "Segment", "struct_gemini_c_p_p_1_1_segment.html", "struct_gemini_c_p_p_1_1_segment" ],
      [ "GroundingSupport", "struct_gemini_c_p_p_1_1_grounding_support.html", "struct_gemini_c_p_p_1_1_grounding_support" ],
      [ "ReviewSnippet", "struct_gemini_c_p_p_1_1_review_snippet.html", "struct_gemini_c_p_p_1_1_review_snippet" ],
      [ "PlaceAnswerSources", "struct_gemini_c_p_p_1_1_place_answer_sources.html", "struct_gemini_c_p_p_1_1_place_answer_sources" ],
      [ "Maps", "struct_gemini_c_p_p_1_1_maps.html", "struct_gemini_c_p_p_1_1_maps" ],
      [ "RetrievedContext", "struct_gemini_c_p_p_1_1_retrieved_context.html", "struct_gemini_c_p_p_1_1_retrieved_context" ],
      [ "Web", "struct_gemini_c_p_p_1_1_web.html", "struct_gemini_c_p_p_1_1_web" ],
      [ "GroundingChunk", "struct_gemini_c_p_p_1_1_grounding_chunk.html", "struct_gemini_c_p_p_1_1_grounding_chunk" ],
      [ "SearchEntryPoint", "struct_gemini_c_p_p_1_1_search_entry_point.html", "struct_gemini_c_p_p_1_1_search_entry_point" ],
      [ "GroundingMetadata", "struct_gemini_c_p_p_1_1_grounding_metadata.html", "struct_gemini_c_p_p_1_1_grounding_metadata" ],
      [ "SemanticRetrieverChunk", "struct_gemini_c_p_p_1_1_semantic_retriever_chunk.html", "struct_gemini_c_p_p_1_1_semantic_retriever_chunk" ],
      [ "GroundingPassageId", "struct_gemini_c_p_p_1_1_grounding_passage_id.html", "struct_gemini_c_p_p_1_1_grounding_passage_id" ],
      [ "AttributionSourceId", "struct_gemini_c_p_p_1_1_attribution_source_id.html", "struct_gemini_c_p_p_1_1_attribution_source_id" ],
      [ "GroundingAttribution", "struct_gemini_c_p_p_1_1_grounding_attribution.html", "struct_gemini_c_p_p_1_1_grounding_attribution" ],
      [ "ResponseCandidate", "struct_gemini_c_p_p_1_1_response_candidate.html", "struct_gemini_c_p_p_1_1_response_candidate" ],
      [ "UsageMetadata", "struct_gemini_c_p_p_1_1_usage_metadata.html", "struct_gemini_c_p_p_1_1_usage_metadata" ],
      [ "PromptFeedback", "struct_gemini_c_p_p_1_1_prompt_feedback.html", "struct_gemini_c_p_p_1_1_prompt_feedback" ],
      [ "GenerateContentRequestBody", "struct_gemini_c_p_p_1_1_generate_content_request_body.html", "struct_gemini_c_p_p_1_1_generate_content_request_body" ],
      [ "StreamGenerateContentRequestBody", "struct_gemini_c_p_p_1_1_stream_generate_content_request_body.html", "struct_gemini_c_p_p_1_1_stream_generate_content_request_body" ],
      [ "GenerateContentResponseBody", "struct_gemini_c_p_p_1_1_generate_content_response_body.html", "struct_gemini_c_p_p_1_1_generate_content_response_body" ],
      [ "StreamGenerateContentResponseBody", "struct_gemini_c_p_p_1_1_stream_generate_content_response_body.html", "struct_gemini_c_p_p_1_1_stream_generate_content_response_body" ],
      [ "ModelInfo", "struct_gemini_c_p_p_1_1_model_info.html", "struct_gemini_c_p_p_1_1_model_info" ],
      [ "ModelsGetRequestBody", "struct_gemini_c_p_p_1_1_models_get_request_body.html", "struct_gemini_c_p_p_1_1_models_get_request_body" ],
      [ "ModelsGetResponseBody", "struct_gemini_c_p_p_1_1_models_get_response_body.html", "struct_gemini_c_p_p_1_1_models_get_response_body" ],
      [ "ModelsListQueryParameters", "struct_gemini_c_p_p_1_1_models_list_query_parameters.html", "struct_gemini_c_p_p_1_1_models_list_query_parameters" ],
      [ "ModelsListRequestBody", "struct_gemini_c_p_p_1_1_models_list_request_body.html", "struct_gemini_c_p_p_1_1_models_list_request_body" ],
      [ "ModelsListResponseBody", "struct_gemini_c_p_p_1_1_models_list_response_body.html", "struct_gemini_c_p_p_1_1_models_list_response_body" ],
      [ "ModelsPredictRequestBody", "struct_gemini_c_p_p_1_1_models_predict_request_body.html", "struct_gemini_c_p_p_1_1_models_predict_request_body" ],
      [ "ModelsPredictResponseBody", "struct_gemini_c_p_p_1_1_models_predict_response_body.html", "struct_gemini_c_p_p_1_1_models_predict_response_body" ],
      [ "ModelsPredictLongRunningRequestBody", "struct_gemini_c_p_p_1_1_models_predict_long_running_request_body.html", "struct_gemini_c_p_p_1_1_models_predict_long_running_request_body" ],
      [ "ModelsPredictLongRunningResponseBody", "struct_gemini_c_p_p_1_1_models_predict_long_running_response_body.html", "struct_gemini_c_p_p_1_1_models_predict_long_running_response_body" ],
      [ "CountTokensRequestBody", "struct_gemini_c_p_p_1_1_count_tokens_request_body.html", "struct_gemini_c_p_p_1_1_count_tokens_request_body" ],
      [ "CountTokensResponseBody", "struct_gemini_c_p_p_1_1_count_tokens_response_body.html", "struct_gemini_c_p_p_1_1_count_tokens_response_body" ],
      [ "IJsonSerializableBase", "struct_gemini_c_p_p_1_1_i_json_serializable_base.html", "struct_gemini_c_p_p_1_1_i_json_serializable_base" ],
      [ "Has_fromJson", "struct_gemini_c_p_p_1_1_has__from_json.html", null ],
      [ "Has_fromJson&lt; T, std::void_t&lt; decltype(T::fromJson(std::declval&lt; const nlohmann::json &amp; &gt;()))&gt; &gt;", "struct_gemini_c_p_p_1_1_has__from_json_3_01_t_00_01std_1_1void__t_3_01decltype_07_t_1_1from_json85acf026d4bc2af93f1a22b2379275aa.html", null ],
      [ "IJsonSerializable", "struct_gemini_c_p_p_1_1_i_json_serializable.html", "struct_gemini_c_p_p_1_1_i_json_serializable" ],
      [ "IsJsonSerializable", "struct_gemini_c_p_p_1_1_is_json_serializable.html", null ],
      [ "IsJsonSerializable&lt; T, std::enable_if_t&lt; std::is_base_of_v&lt; IJsonSerializable&lt; T &gt;, T &gt; &gt; &gt;", "struct_gemini_c_p_p_1_1_is_json_serializable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__bas80aa3d5ec55c2bad7bffa06d0994fb65.html", null ],
      [ "ResourceName", "class_gemini_c_p_p_1_1_resource_name.html", "class_gemini_c_p_p_1_1_resource_name" ],
      [ "Url", "class_gemini_c_p_p_1_1_url.html", "class_gemini_c_p_p_1_1_url" ],
      [ "Utils", "class_gemini_c_p_p_1_1_utils.html", null ],
      [ "Uuid", "class_gemini_c_p_p_1_1_uuid.html", null ]
    ] ]
];