var caching__api__types_8h =
[
    [ "GeminiCPP::FunctionResponsePart", "struct_gemini_c_p_p_1_1_function_response_part.html", "struct_gemini_c_p_p_1_1_function_response_part" ],
    [ "GeminiCPP::TextData", "struct_gemini_c_p_p_1_1_text_data.html", "struct_gemini_c_p_p_1_1_text_data" ],
    [ "GeminiCPP::Blob", "struct_gemini_c_p_p_1_1_blob.html", "struct_gemini_c_p_p_1_1_blob" ],
    [ "GeminiCPP::FunctionCall", "struct_gemini_c_p_p_1_1_function_call.html", "struct_gemini_c_p_p_1_1_function_call" ],
    [ "GeminiCPP::FunctionResponse", "struct_gemini_c_p_p_1_1_function_response.html", "struct_gemini_c_p_p_1_1_function_response" ],
    [ "GeminiCPP::FileData", "struct_gemini_c_p_p_1_1_file_data.html", "struct_gemini_c_p_p_1_1_file_data" ],
    [ "GeminiCPP::ExecutableCode", "struct_gemini_c_p_p_1_1_executable_code.html", "struct_gemini_c_p_p_1_1_executable_code" ],
    [ "GeminiCPP::CodeExecutionResult", "struct_gemini_c_p_p_1_1_code_execution_result.html", "struct_gemini_c_p_p_1_1_code_execution_result" ],
    [ "GeminiCPP::VideoMetadata", "struct_gemini_c_p_p_1_1_video_metadata.html", "struct_gemini_c_p_p_1_1_video_metadata" ],
    [ "GeminiCPP::Part", "struct_gemini_c_p_p_1_1_part.html", "struct_gemini_c_p_p_1_1_part" ],
    [ "GeminiCPP::Content", "struct_gemini_c_p_p_1_1_content.html", "struct_gemini_c_p_p_1_1_content" ],
    [ "GeminiCPP::FunctionCallingConfig", "struct_gemini_c_p_p_1_1_function_calling_config.html", "struct_gemini_c_p_p_1_1_function_calling_config" ],
    [ "GeminiCPP::LatLng", "struct_gemini_c_p_p_1_1_lat_lng.html", "struct_gemini_c_p_p_1_1_lat_lng" ],
    [ "GeminiCPP::RetrievalConfig", "struct_gemini_c_p_p_1_1_retrieval_config.html", "struct_gemini_c_p_p_1_1_retrieval_config" ],
    [ "GeminiCPP::ToolConfig", "struct_gemini_c_p_p_1_1_tool_config.html", "struct_gemini_c_p_p_1_1_tool_config" ],
    [ "GeminiCPP::FunctionDeclaration", "struct_gemini_c_p_p_1_1_function_declaration.html", "struct_gemini_c_p_p_1_1_function_declaration" ],
    [ "GeminiCPP::GoogleSearch", "struct_gemini_c_p_p_1_1_google_search.html", "struct_gemini_c_p_p_1_1_google_search" ],
    [ "GeminiCPP::GoogleMaps", "struct_gemini_c_p_p_1_1_google_maps.html", "struct_gemini_c_p_p_1_1_google_maps" ],
    [ "GeminiCPP::CodeExecution", "struct_gemini_c_p_p_1_1_code_execution.html", "struct_gemini_c_p_p_1_1_code_execution" ],
    [ "GeminiCPP::Tool", "struct_gemini_c_p_p_1_1_tool.html", "struct_gemini_c_p_p_1_1_tool" ],
    [ "GeminiCPP::CachedContentUsageMetadata", "struct_gemini_c_p_p_1_1_cached_content_usage_metadata.html", "struct_gemini_c_p_p_1_1_cached_content_usage_metadata" ],
    [ "GeminiCPP::CachedContent", "struct_gemini_c_p_p_1_1_cached_content.html", "struct_gemini_c_p_p_1_1_cached_content" ],
    [ "GeminiCPP::ListCachedContentsResponse", "struct_gemini_c_p_p_1_1_list_cached_contents_response.html", "struct_gemini_c_p_p_1_1_list_cached_contents_response" ],
    [ "GEMINI_CACHING_API_TYPES_H", "caching__api__types_8h.html#a94161558c0fde7eecb938140bb8414de", null ],
    [ "GeminiCPP::FrenumClassInNamespace", "namespace_gemini_c_p_p.html#acf32fc540f17206915ac1b8e84e8f481", null ],
    [ "GeminiCPP::FrenumClassInNamespace", "namespace_gemini_c_p_p.html#ad19c1fa82e817145833f3022097519e9", null ],
    [ "GeminiCPP::FrenumClassInNamespace", "namespace_gemini_c_p_p.html#a8f9d295922bb040ce0b2d8fa195a6c4e", null ],
    [ "GeminiCPP::Language", "namespace_gemini_c_p_p.html#a9273433e92fd6ab1bd595a3c2ec0a410", null ],
    [ "GeminiCPP::LANGUAGE_UNSPECIFIED", "namespace_gemini_c_p_p.html#a46858fc837269039f667aa7a242bce67", null ],
    [ "GeminiCPP::MODEL", "namespace_gemini_c_p_p.html#a37ff9d5e1a76a57031e9e62dc2765257", null ],
    [ "GeminiCPP::Role", "namespace_gemini_c_p_p.html#ae60c3c6675d22c755d9f483cd3057778", null ],
    [ "GeminiCPP::uint8_t", "namespace_gemini_c_p_p.html#a67b60949cc5e2c9c29ae5f9f4c669513", null ],
    [ "GeminiCPP::USER", "namespace_gemini_c_p_p.html#afaff8d7fc3ed8cd2f4cfb40df4fc261f", null ]
];